### ISSUE TITLE
Provide initial guidance on "front page"

### ISSUE THREAD

**Issue by adam3smith** [QualitativeDataRepository/AnnoREP-Frontend#19]
## Use Case

Researchers should get a quick overview of the entire AnnoREP workflow from the start, ideally using a simple infographic 

## Solution

We can provide the infographic, but the question is where exactly it sits in terms of the AnnoREP structure.

**Comment by nniiicc** [comment]
@adam3smith - What are the steps you want to depict here: 1. Upload Manuscript; 2. Connect Data Collection; 3. Create Annotations; 4. Export ATI project

**Comment by tohuynh** [comment]
It might also be helpful to elaborate on what is being used to facilitate the annotation workflow? That is AnnoRep store data sources and manuscript on QDR and use Hypothesis to store and display annotations to allow users to edit/write annotations.

There should be a `Submit for review step that needs elaboration too.

**Comment by adam3smith** [comment]
I'm thinking (but this isn't authoritative in any way):

1. Annotate your manuscript with the tools you know
2. Upload to AnnoREP
3. Connect a data project on QDR
4. Review and Edit your annotations
5. a) Submit your annotations for Review
b) Copy your annotations to a copy of your paper anywhere on the web 
6 a) Have your data and annotations published by QDR 

> That is AnnoRep store data sources and manuscript on QDR and use Hypothesis to store and display annotations to allow users to edit/write annotations.

I wonder if we could maybe achieve this just by smartly using graphics/icons, such as a hypothesis logo for ATI annos etc.

**Comment by tohuynh** [comment]
> I wonder if we could maybe achieve this just by smartly using graphics/icons, such as a hypothesis logo for ATI annos etc.

👍

**Comment by adam3smith** [comment]
OK, here's a first draft from me: Image
![AnnoREP Workflow](https://user-images.githubusercontent.com/128986/149018732-29214dca-f02a-4b78-9a8d-8dc3ac55fb47.png)

Powerpoint:
[AnnoREP Workflow.pptx](https://github.com/adam3smith/AnnoREP-Frontend/files/7849769/AnnoREP.Workflow.pptx)

I like the headings and the flow, I think the screenshots have too much text. I think we should abstract them, maybe even with simple drawings?

**Comment by tohuynh** [comment]
These look good. I would implement this as a single-column flow, rather than two columns with the arrows. Are you OK with that?

For some of the steps, I don't think screenshots from app are needed. I think we could just link the pages of the app or add more text?

3 Link to login page instead of a screenshot
4 Link to create new ATI page instead of a screenshot
5-6: Not sure what to do

5 "Navigate to the `Manuscript` tab of your newly created ATI project to add, edit, or remove annotations" (Note: once the user creates an ATI project, the app redirects them to that specific ATI's page). Here we can link to instructions on how to use the Annotation sidebar. Is there such a resource like a video or some step-by-step instructions from Hypothesis?
6-a. "Navigate to the `Summary` tab of your ATI project to submit your project for review & publication by QDR​." I'm fine with the provided screenshot.
6-b. "Navigate to the `Export annotations`  tab of your ATI project to copy your ATI annotations to a copy of your manuscript anywhere on the web​"

What do you think of these texts?

**Comment by adam3smith** [comment]
Thanks To -- definitely fine with a single column flow, yes.
I think links where they exist make sense, yes. For the suggested text, I think this may be something worth testing. My goal with the figure is to give people a sense of the "flow" of the app quickly, so I'm trying to not overwhelm them with technical details. My hope is that the app itself is fairly self-explanatory. I also would like to keep 1 visual per step to keep things light and visual and not too text heavy. 

Here's another/alternate version that I quite like with a more "sketched" look to it. 
![AnnoREP Workflow_sketched](https://user-images.githubusercontent.com/128986/149052753-1f668338-1aa4-4a85-831d-8ba2e332c545.png)
The designs here are all written, so better for accessibility. The Rock Sands font is in google fonts (as al alternative I also like Permanent Marker)

Powerpoint has this on p. 2.
[AnnoREP Workflow.pptx](https://github.com/adam3smith/AnnoREP-Frontend/files/7851207/AnnoREP.Workflow.pptx)

**Comment by tohuynh** [comment]
I'm happy to use these sketches. Would you prefer to display the sketches as images or re-create them as HTML?

If images, could you provide an individual file for each sketch?

For the HTML option, all the sketches can be easily created, except for step 2 (because of the comment bubble). But I think it's possible, I'd probably just need to google for a solution.

**Comment by adam3smith** [comment]
[Anno-REP images.zip](https://github.com/adam3smith/AnnoREP-Frontend/files/7872887/Anno-REP.images.zip)

Let's go with the images for now (zip file above) -- since we may change that based on feedback, not worth investing too much time in html-ifying, though really appreciate the offer.

**Comment by tohuynh** [comment]
> since we may change that based on feedback, not worth investing too much time in html-ifying

👍

**Comment by tohuynh** [comment]
Here's a draft of the new home page (user logged out):
![image](https://user-images.githubusercontent.com/37560480/150210547-ddb7f993-739b-46ec-afe9-43c84a3b514e.png)

- The Hypothesis image for step 1 needs to be fixed. Notice the missing "H"
- "Guide" in the app bar links to the `/guide` page of the app, which contains exactly the same information as the home page (user logged out)
- Decided to go with 2 columns without arrows. The images are best suited for two columns and I think the numbers makes it clear on the order of the flow without needing the arrows.
- "learn more about ATI" leads to https://qdr.syr.edu/ati in a new tab
- "login to create a new project" leads to the login page of the app. Note: When the user is logged in and visit `/guide` page, the primary blue button is "Create a new ATI project", which leads to the `/new` page.

@nniiicc @adam3smith Any feedback or thoughts?

**Comment by tohuynh** [comment]
I want to include these two external resources on the page:
- https://qdr.syr.edu/qdr-resources
- https://web.hypothes.is/help/annotation-basics/

Any thoughts on whether the app should link them and where to place the links?

**Comment by adam3smith** [comment]
![hypothesis](https://user-images.githubusercontent.com/128986/151903938-b253fe5f-e659-4834-af63-4aa4a876dff8.png)

OK, fixed Hypothes.is image here

> I want to include these two external resources on the page:

I wouldn't link to qdr-resources: I'm worried those are too general.
Maybe link to the hypothes.is docs from panel 5?

**Comment by tohuynh** [comment]
> I wouldn't link to qdr-resources: I'm worried those are too general.
Maybe link to the hypothes.is docs from panel 5?

sounds good
